In [1]:
import numpy as np


In [2]:
l = [1, 2, 3, 4]
type(l)


list

In [3]:
ar = np.array(l)


In [4]:
print(ar)
type(ar)


[1 2 3 4]


numpy.ndarray

In [5]:
np.asarray(l)


array([1, 2, 3, 4])

In [6]:
np.asanyarray(l)


array([1, 2, 3, 4])

In [7]:
b = np.matrix(l)


In [8]:
b


matrix([[1, 2, 3, 4]])

In [9]:
type(b)


numpy.matrix

In [10]:
a = np.array(l)


In [11]:
a


array([1, 2, 3, 4])

In [12]:
c = a
c


array([1, 2, 3, 4])

In [13]:
a


array([1, 2, 3, 4])

In [14]:
c[0] = 100  # Here c and a are vice versa..They are directly prepotinal ...It refers same address


In [15]:
a


array([100,   2,   3,   4])

In [16]:
c


array([100,   2,   3,   4])

In [17]:
d = np.copy(a)  # Here d and a are refers different address


In [18]:
d


array([100,   2,   3,   4])

In [19]:
d[0] = 200
d


array([200,   2,   3,   4])

In [20]:
a


array([100,   2,   3,   4])

In [21]:
result = np.fromfunction(lambda i, j: (print(i, j), i == j), (3, 3))


[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]] [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [22]:
result = np.fromfunction(lambda i, j: i == j, (3, 3))
result


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:

result = np.fromfunction(lambda i, j: (
    print(f"i: {i}, j: {j}"), i == j), (3, 3))
print(result)


i: [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]], j: [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
(None, array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]]))


In [26]:
import numpy as np
np.fromfunction(lambda i, j: i*j, (3, 3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
iterable = (i*i for i in range(5))
# np.fromiter(iterable, float)


In [28]:
intVal = np.fromiter(iterable, int)
intVal


array([ 0,  1,  4,  9, 16])

In [29]:
intVal


array([ 0,  1,  4,  9, 16])

In [30]:
np.fromstring("1234 5678", sep=" ")


array([1234., 5678.])

In [31]:
l1 = [[1, 2, 3, 4], [5, 6, 7, 8]]


In [32]:
arr1 = np.array(l1)
arr1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
arr2 = np.array([[101, 102, 103], [201, 202, 203]])
arr2


array([[101, 102, 103],
       [201, 202, 203]])

In [65]:
arr2.ndim


2

In [34]:
arr1.size


8

In [35]:
arr2.size


6

In [36]:
arr1.shape


(2, 4)

In [37]:
arr2.shape


(2, 3)

In [38]:
arr2.dtype


dtype('int32')

In [68]:
arr3 = np.array([(1.4, 2, 3, 4, 5), (9, 8, 7, 6, 12)])
arr3
arr3.dtype


dtype('float64')

In [40]:
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [42]:
list(np.arange(1.5, 11.2, 1.2))


[1.5,
 2.7,
 3.9000000000000004,
 5.1000000000000005,
 6.300000000000001,
 7.500000000000001,
 8.700000000000001,
 9.900000000000002,
 11.100000000000001]

In [44]:
np.linspace(0, 100, 21)


array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [69]:
np.linspace(1, 10, 10)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
np.zeros([3, 4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# Here 1st Parameter(3)=No. of matrix  2nd Parameter(4)=No.of rows in matrix  3rd Parameter(5)=No.of columns in matrix
np.zeros([3, 5, 3])


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
# Here 1st Parameter(2)=No. of matrix copies you  hava 2nd Parameter(3)=No.of matrix 3rd Parameter(2)=No.of rows in matrix  3rd Parameter(5)=No.of columns in matrix
np.zeros([2, 3, 2, 3])


array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [47]:
np.ones((5, 3, 2))


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [48]:
on = np.ones((2, 4, 4))
on


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
on+4


array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [51]:
np.empty((3, 2))


array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [71]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
np.logspace(2, 5, base=2)


array([ 4.        ,  4.17340372,  4.35432466,  4.54308869,  4.74003581,
        4.94552078,  5.15991371,  5.38360077,  5.61698488,  5.8604864 ,
        6.11454394,  6.37961511,  6.65617737,  6.94472885,  7.24578931,
        7.55990103,  7.88762977,  8.22956587,  8.58632521,  8.9585504 ,
        9.3469119 ,  9.75210923, 10.17487225, 10.61596243, 11.07617429,
       11.55633675, 12.05731471, 12.58001053, 13.1253657 , 13.69436252,
       14.28802588, 14.90742511, 15.55367586, 16.22794219, 16.93143859,
       17.66543222, 18.43124515, 19.23025679, 20.06390632, 20.93369534,
       21.84119052, 22.78802646, 23.77590863, 24.8066164 , 25.88200631,
       27.00401538, 28.17466459, 29.39606253, 30.67040921, 32.        ])

In [54]:
arr = np.random.rand(2, 3)
arr


array([[0.91196694, 0.82593357, 0.97866506],
       [0.07902735, 0.35201755, 0.61038896]])

In [55]:
randArr1 = np.random.randint(1, 100, (3, 4))
randArr1


array([[50, 74, 89, 46],
       [29, 88, 23, 50],
       [43, 17, 17, 47]])

In [76]:
randArr2 = np.random.randint(1, 10, (5, 5))
randArr2


array([[5, 6, 8, 9, 8],
       [6, 2, 8, 3, 9],
       [1, 4, 9, 2, 5],
       [8, 4, 5, 4, 1],
       [1, 5, 5, 6, 3]])

In [56]:
import pandas as pd
df1 = pd.DataFrame(randArr1).to_csv("randomData.csv")
df3 = pd.read_csv("randomData.csv")
df3.head()


Unnamed: 0   0   1   2   3
0           0  50  74  89  46
1           1  29  88  23  50
2           2  43  17  17  47

In [57]:
df1


In [58]:
df2 = pd.DataFrame(arr)


In [59]:
df2


0         1         2
0  0.911967  0.825934  0.978665
1  0.079027  0.352018  0.610389

In [77]:
arr5 = np.random.rand(3, 4)
arr5


array([[0.16922525, 0.05839939, 0.44491097, 0.3725324 ],
       [0.92990627, 0.38576597, 0.26172575, 0.69468776],
       [0.45879231, 0.63634667, 0.11293189, 0.38629692]])

In [92]:
arr6 = arr5.reshape(6, 2)
arr6


array([[0.16922525, 0.05839939],
       [0.44491097, 0.3725324 ],
       [0.92990627, 0.38576597],
       [0.26172575, 0.69468776],
       [0.45879231, 0.63634667],
       [0.11293189, 0.38629692]])

In [101]:
arr6[5][0]


0.11293188844635804

In [108]:
arr7 = np.random.randint(1, 100, (6, 7))
arr7


array([[ 8,  5, 81, 22, 73, 24, 91],
       [79,  9, 34, 92, 81, 61, 94],
       [19, 12, 53, 96, 95,  6, 59],
       [49, 72, 46, 28, 20, 98, 99],
       [72, 79, 99, 63, 49, 63, 10],
       [39, 86, 99, 38, 65, 38, 63]])

In [121]:
arr7[0:, 2]


array([81, 34, 53, 46, 99, 99])

In [125]:
arr7[4][1:5]


array([79, 99, 63, 49])

In [126]:
arr7


array([[ 8,  5, 81, 22, 73, 24, 91],
       [79,  9, 34, 92, 81, 61, 94],
       [19, 12, 53, 96, 95,  6, 59],
       [49, 72, 46, 28, 20, 98, 99],
       [72, 79, 99, 63, 49, 63, 10],
       [39, 86, 99, 38, 65, 38, 63]])

In [141]:
arr7[arr7 < 10]


array([8, 5, 9, 6])

In [136]:
arr7[1:3, 3:-1]


array([[92, 81, 61],
       [96, 95,  6]])

In [150]:
cal1 = np.random.randint(1, 3, (3, 3))
print(cal1)
cal2 = np.random.randint(1, 3, (3, 3))
print("\n", cal2)

print("\nAddition\n")
print(cal1+cal2)
print("\nSubstraction\n")
print(cal1-cal2)
print("\nDivision\n")
print(cal1/cal2)


[[1 1 1]
 [2 2 2]
 [2 2 2]]

 [[1 1 2]
 [2 1 1]
 [2 1 1]]

Addition

[[2 2 3]
 [4 3 3]
 [4 3 3]]

Substraction

[[ 0  0 -1]
 [ 0  1  1]
 [ 0  1  1]]

Division

[[1.  1.  0.5]
 [1.  2.  2. ]
 [1.  2.  2. ]]


In [151]:
print("\nMultiplication\n")
print(cal1@cal2)



Multiplication

[[ 5  3  4]
 [10  6  8]
 [10  6  8]]


In [164]:
# Row wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([1, 2, 3, 4])
print(row)
b1+row


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 2 3 4]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [162]:
# Column wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([[1, 2, 3, 4]])
print(row)
row.T
print(row)
b1+row


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 2 3 4]]
[[1 2 3 4]]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [160]:
a1 = np.random.randint(1, 3, (3, 3))
a1


array([[2, 2, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [165]:
np.sqrt(a1)


array([[1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [166]:
np.exp(a1)


array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [167]:
np.log10(a1)


array([[0.30103, 0.30103, 0.30103],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])