In [79]:
import numpy as np


In [3]:
l = [1, 2, 3, 4]
type(l)


list

In [4]:
ar = np.array(l)


In [5]:
print(ar)
type(ar)


[1 2 3 4]


numpy.ndarray

In [6]:
np.asarray(l)


array([1, 2, 3, 4])

In [7]:
np.asanyarray(l)


array([1, 2, 3, 4])

In [8]:
b = np.matrix(l)


In [9]:
b


matrix([[1, 2, 3, 4]])

In [10]:
type(b)


numpy.matrix

In [11]:
a = np.array(l)


In [12]:
a


array([1, 2, 3, 4])

In [13]:
c = a
c


array([1, 2, 3, 4])

In [14]:
a


array([1, 2, 3, 4])

In [15]:
c[0] = 100  # Here c and a are vice versa..They are directly prepotinal ...It refers same address


In [16]:
a


array([100,   2,   3,   4])

In [17]:
c


array([100,   2,   3,   4])

In [18]:
d = np.copy(a)  # Here d and a are refers different address


In [19]:
d


array([100,   2,   3,   4])

In [20]:
d[0] = 200
d


array([200,   2,   3,   4])

In [21]:
a


array([100,   2,   3,   4])

In [22]:
result = np.fromfunction(lambda i, j: (print(i, j), i == j), (3, 3))


[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]] [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [23]:
result = np.fromfunction(lambda i, j: i == j, (3, 3))
result


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:

result = np.fromfunction(lambda i, j: (
    print(f"i: {i}, j: {j}"), i == j), (3, 3))
print(result)


i: [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]], j: [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
(None, array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]]))


In [25]:
import numpy as np
np.fromfunction(lambda i, j: i*j, (3, 3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [26]:
iterable = (i*i for i in range(5))
# np.fromiter(iterable, float)


In [27]:
intVal = np.fromiter(iterable, int)
intVal


array([ 0,  1,  4,  9, 16])

In [28]:
intVal


array([ 0,  1,  4,  9, 16])

In [29]:
np.fromstring("1234 5678", sep=" ")


array([1234., 5678.])

In [30]:
l1 = [[1, 2, 3, 4], [5, 6, 7, 8]]


In [31]:
arr1 = np.array(l1)
arr1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr2 = np.array([[101, 102, 103], [201, 202, 203]])
arr2


array([[101, 102, 103],
       [201, 202, 203]])

In [33]:
arr2.ndim


2

In [34]:
arr1.size


8

In [35]:
arr2.size


6

In [36]:
arr1.shape


(2, 4)

In [37]:
arr2.shape


(2, 3)

In [38]:
arr2.dtype


dtype('int32')

In [39]:
arr3 = np.array([(1.4, 2, 3, 4, 5), (9, 8, 7, 6, 12)])
arr3
arr3.dtype


dtype('float64')

In [40]:
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [41]:
list(np.arange(1.5, 11.2, 1.2))


[1.5,
 2.7,
 3.9000000000000004,
 5.1000000000000005,
 6.300000000000001,
 7.500000000000001,
 8.700000000000001,
 9.900000000000002,
 11.100000000000001]

In [42]:
np.linspace(0, 100, 21)


array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [43]:
np.linspace(1, 10, 10)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
np.zeros([3, 4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
# Here 1st Parameter(3)=No. of matrix  2nd Parameter(4)=No.of rows in matrix  3rd Parameter(5)=No.of columns in matrix
np.zeros([3, 5, 3])


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
# Here 1st Parameter(2)=No. of matrix copies you  hava 2nd Parameter(3)=No.of matrix 3rd Parameter(2)=No.of rows in matrix  3rd Parameter(5)=No.of columns in matrix
np.zeros([2, 3, 2, 3])


array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [47]:
np.ones((5, 3, 2))


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [48]:
on = np.ones((2, 4, 4))
on


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
on+4


array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [50]:
np.empty((3, 2))


array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [51]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.logspace(2, 5, base=2)


array([ 4.        ,  4.17340372,  4.35432466,  4.54308869,  4.74003581,
        4.94552078,  5.15991371,  5.38360077,  5.61698488,  5.8604864 ,
        6.11454394,  6.37961511,  6.65617737,  6.94472885,  7.24578931,
        7.55990103,  7.88762977,  8.22956587,  8.58632521,  8.9585504 ,
        9.3469119 ,  9.75210923, 10.17487225, 10.61596243, 11.07617429,
       11.55633675, 12.05731471, 12.58001053, 13.1253657 , 13.69436252,
       14.28802588, 14.90742511, 15.55367586, 16.22794219, 16.93143859,
       17.66543222, 18.43124515, 19.23025679, 20.06390632, 20.93369534,
       21.84119052, 22.78802646, 23.77590863, 24.8066164 , 25.88200631,
       27.00401538, 28.17466459, 29.39606253, 30.67040921, 32.        ])

In [53]:
arr = np.random.rand(2, 3)
arr


array([[0.08631415, 0.52627579, 0.27296133],
       [0.58776839, 0.99631843, 0.64428577]])

In [54]:
randArr1 = np.random.randint(1, 100, (3, 4))
randArr1


array([[37, 63, 99, 70],
       [59, 36, 55, 33],
       [92, 24, 30, 31]])

In [55]:
randArr2 = np.random.randint(1, 10, (5, 5))
randArr2


array([[5, 6, 2, 6, 8],
       [2, 3, 4, 7, 7],
       [9, 6, 8, 9, 9],
       [7, 2, 2, 7, 1],
       [7, 5, 2, 2, 6]])

In [56]:
import pandas as pd
df1 = pd.DataFrame(randArr1).to_csv("randomData.csv")
df3 = pd.read_csv("randomData.csv")
df3.head()


Unnamed: 0   0   1   2   3
0           0  37  63  99  70
1           1  59  36  55  33
2           2  92  24  30  31

In [57]:
df1


In [58]:
df2 = pd.DataFrame(arr)


In [59]:
df2


0         1         2
0  0.086314  0.526276  0.272961
1  0.587768  0.996318  0.644286

In [60]:
arr5 = np.random.rand(3, 4)
arr5


array([[0.9681655 , 0.98914515, 0.55672254, 0.95321637],
       [0.60609917, 0.6592378 , 0.54560068, 0.22041792],
       [0.4759154 , 0.6882361 , 0.61545834, 0.01252762]])

In [61]:
arr6 = arr5.reshape(6, 2)
arr6


array([[0.9681655 , 0.98914515],
       [0.55672254, 0.95321637],
       [0.60609917, 0.6592378 ],
       [0.54560068, 0.22041792],
       [0.4759154 , 0.6882361 ],
       [0.61545834, 0.01252762]])

In [62]:
arr6[5][0]


0.6154583421445992

In [63]:
arr7 = np.random.randint(1, 100, (6, 7))
arr7


array([[65, 36, 29, 85, 93, 30, 19],
       [39, 69,  2, 96, 20, 42, 88],
       [10, 71, 75, 52, 41, 49, 52],
       [89, 63,  3, 92, 21, 29,  8],
       [15, 45, 47, 98, 54, 39, 62],
       [40, 32, 70, 74, 32, 60, 72]])

In [64]:
arr7[0:, 2]


array([29,  2, 75,  3, 47, 70])

In [65]:
arr7[4][1:5]


array([45, 47, 98, 54])

In [66]:
arr7


array([[65, 36, 29, 85, 93, 30, 19],
       [39, 69,  2, 96, 20, 42, 88],
       [10, 71, 75, 52, 41, 49, 52],
       [89, 63,  3, 92, 21, 29,  8],
       [15, 45, 47, 98, 54, 39, 62],
       [40, 32, 70, 74, 32, 60, 72]])

In [67]:
arr7[arr7 < 10]


array([2, 3, 8])

In [68]:
arr7[1:3, 3:-1]


array([[96, 20, 42],
       [52, 41, 49]])

In [69]:
cal1 = np.random.randint(1, 3, (3, 3))
print(cal1)
cal2 = np.random.randint(1, 3, (3, 3))
print("\n", cal2)

print("\nAddition\n")
print(cal1+cal2)
print("\nSubstraction\n")
print(cal1-cal2)
print("\nDivision\n")
print(cal1/cal2)


[[1 2 2]
 [2 2 2]
 [2 2 2]]

 [[2 1 2]
 [1 2 2]
 [1 2 2]]

Addition

[[3 3 4]
 [3 4 4]
 [3 4 4]]

Substraction

[[-1  1  0]
 [ 1  0  0]
 [ 1  0  0]]

Division

[[0.5 2.  1. ]
 [2.  1.  1. ]
 [2.  1.  1. ]]


In [70]:
print("\nMultiplication\n")
print(cal1@cal2)



Multiplication

[[ 6  9 10]
 [ 8 10 12]
 [ 8 10 12]]


In [71]:
# Row wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([1, 2, 3, 4])
print(row)
b1+row


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 2 3 4]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [72]:
# Column wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([[1, 2, 3, 4]])
print(row)
row.T
print(row)
b1+row


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 2 3 4]]
[[1 2 3 4]]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [73]:
a1 = np.random.randint(1, 3, (3, 3))
a1


array([[1, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [74]:
np.sqrt(a1)


array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [75]:
np.exp(a1)


array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [76]:
np.log10(a1)


array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [81]:
a2 = np.array([4, 3, 5, 6, 3, 4, 5, 9, 1, 4, 5, 34, 543])
a2


array([  4,   3,   5,   6,   3,   4,   5,   9,   1,   4,   5,  34, 543])

In [82]:
np.sort(a2)


array([  1,   3,   3,   4,   4,   4,   5,   5,   5,   6,   9,  34, 543])

In [94]:
np.searchsorted(a2, 30)


11

In [95]:
a3 = np.array([34, 5, 6, 23, 0, 0, 66, 78, 0, 0, 0, 0, 0])
a3


array([34,  5,  6, 23,  0,  0, 66, 78,  0,  0,  0,  0,  0])

In [96]:
np.count_nonzero(a3)


6

In [97]:
np.where(a3 > 0)


(array([0, 1, 2, 3, 6, 7], dtype=int64),)

In [102]:
a3.byteswap()


array([ 570425344,   83886080,  100663296,  385875968,          0,
                0, 1107296256, 1308622848,          0,          0,
                0,          0,          0])

In [104]:
np.extract(a3 > 0, a3)


array([34,  5,  6, 23, 66, 78])

In [106]:
a4 = np.array([23, 4, 5, 67, 43, 232, 5667])
a4


array([  23,    4,    5,   67,   43,  232, 5667])

In [108]:
c1 = np.copy(a4)  # Deep copy
c1


array([  23,    4,    5,   67,   43,  232, 5667])

In [109]:
c1[0] = 100


In [113]:
print(c1)
print(a4)


[ 100    4    5   67   43  232 5667]
[  23    4    5   67   43  232 5667]


In [115]:
c2 = a4.view()  # shadow copy


In [116]:
print(c2)
print(a4)


[  23    4    5   67   43  232 5667]
[  23    4    5   67   43  232 5667]


In [117]:
c2[0] = 200


In [118]:
print(c2)
print(a4)


[ 200    4    5   67   43  232 5667]
[ 200    4    5   67   43  232 5667]


In [119]:
import numpy.matlib as nm


In [123]:
nm.zeros((2, 3))


matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [124]:
a5 = nm.ones((3, 4))


matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [127]:
nm.eye(4)


matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [135]:
m1 = np.random.randint(1, 10, (3, 3))
m1


array([[7, 7, 6],
       [5, 7, 2],
       [6, 6, 1]])

In [138]:
m2 = np.random.randint(1, 10, (3, 3))
m2


array([[8, 2, 9],
       [3, 3, 6],
       [5, 7, 4]])

In [139]:
np.dot(m1, m2)


array([[107,  77, 129],
       [ 71,  45,  95],
       [ 71,  37,  94]])

In [140]:
arr.flatten()


array([0.08631415, 0.52627579, 0.27296133, 0.58776839, 0.99631843,
       0.64428577])

In [141]:
arr


array([[0.08631415, 0.52627579, 0.27296133],
       [0.58776839, 0.99631843, 0.64428577]])

In [144]:
a7 = np.array([5, 3, 34, 54, 54, 545])
np.expand_dims(a7, axis=0)


array([[  5,   3,  34,  54,  54, 545]])

In [145]:
np.expand_dims(a7, axis=1)


array([[  5],
       [  3],
       [ 34],
       [ 54],
       [ 54],
       [545]])

In [149]:
a8 = np.array((1, 2, 3, 4), (5, 6, 7, 8))
np.squeeze(a8)


TypeError: Tuple must have size 2, but has size 4

In [151]:
np.repeat(a7, 2)


array([  5,   5,   3,   3,  34,  34,  54,  54,  54,  54, 545, 545])

In [ ]:
np.rol


In [154]:
np.diag(a7)


array([[  5,   0,   0,   0,   0,   0],
       [  0,   3,   0,   0,   0,   0],
       [  0,   0,  34,   0,   0,   0],
       [  0,   0,   0,  54,   0,   0],
       [  0,   0,   0,   0,  54,   0],
       [  0,   0,   0,   0,   0, 545]])

In [155]:
m3 = np.random.randint(1, 7, (4, 4))
print(m3)
print("\n\n")
m4 = np.random.randint(5, 10, (4, 4))
print(m4)


[[2 3 6 2]
 [2 4 2 6]
 [4 6 2 1]
 [3 1 2 4]]



[[9 6 7 8]
 [9 6 6 6]
 [9 7 8 5]
 [6 8 6 8]]


In [156]:
m3+m4


array([[11,  9, 13, 10],
       [11, 10,  8, 12],
       [13, 13, 10,  6],
       [ 9,  9,  8, 12]])

In [158]:
m4-m3


array([[7, 3, 1, 6],
       [7, 2, 4, 0],
       [5, 1, 6, 4],
       [3, 7, 4, 4]])

In [160]:
m3*m4


array([[18, 18, 42, 16],
       [18, 24, 12, 36],
       [36, 42, 16,  5],
       [18,  8, 12, 32]])

In [162]:
m4/m3


array([[4.5       , 2.        , 1.16666667, 4.        ],
       [4.5       , 1.5       , 3.        , 1.        ],
       [2.25      , 1.16666667, 4.        , 5.        ],
       [2.        , 8.        , 3.        , 2.        ]])

In [163]:
m4 % m3


array([[1, 0, 1, 0],
       [1, 2, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0]])

In [165]:
m4**m3  # IT'S CALCULATE POWER


array([[    81,    216, 117649,     64],
       [    81,   1296,     36,  46656],
       [  6561, 117649,     64,      5],
       [   216,      8,     36,   4096]])

In [166]:
m3 & m4


array([[0, 2, 6, 0],
       [0, 4, 2, 6],
       [0, 6, 0, 1],
       [2, 0, 2, 0]])

In [167]:
print(f"{m3}\n{m4}")


[[2 3 6 2]
 [2 4 2 6]
 [4 6 2 1]
 [3 1 2 4]]
[[9 6 7 8]
 [9 6 6 6]
 [9 7 8 5]
 [6 8 6 8]]


In [168]:
-m4


array([[-9, -6, -7, -8],
       [-9, -6, -6, -6],
       [-9, -7, -8, -5],
       [-6, -8, -6, -8]])

In [174]:
s1 = np.array(["sarvajit", "Mangesh", "vaibhav", "Saurabh"])
s1


array(['sarvajit', 'Mangesh', 'vaibhav', 'Saurabh'], dtype='<U8')

In [175]:
np.char.upper(s1)


array(['SARVAJIT', 'MANGESH', 'VAIBHAV', 'SAURABH'], dtype='<U8')

In [176]:
np.char.title(s1)


array(['Sarvajit', 'Mangesh', 'Vaibhav', 'Saurabh'], dtype='<U8')

In [177]:
np.char.capitalize(s1)


array(['Sarvajit', 'Mangesh', 'Vaibhav', 'Saurabh'], dtype='<U8')

array(['sarvajit', 'Mangesh', 'vaibhav', 'Saurabh'], dtype='<U8')

In [181]:
# Mathematical operations
math1 = np.random.randint(1, 7, (3, 4))
math1


array([[1, 6, 5, 3],
       [4, 2, 2, 3],
       [2, 6, 1, 4]])

In [182]:
np.sin(math1)


array([[ 0.84147098, -0.2794155 , -0.95892427,  0.14112001],
       [-0.7568025 ,  0.90929743,  0.90929743,  0.14112001],
       [ 0.90929743, -0.2794155 ,  0.84147098, -0.7568025 ]])

In [183]:
np.cos(math1)


array([[ 0.54030231,  0.96017029,  0.28366219, -0.9899925 ],
       [-0.65364362, -0.41614684, -0.41614684, -0.9899925 ],
       [-0.41614684,  0.96017029,  0.54030231, -0.65364362]])

In [184]:
np.log10(math1)


array([[0.        , 0.77815125, 0.69897   , 0.47712125],
       [0.60205999, 0.30103   , 0.30103   , 0.47712125],
       [0.30103   , 0.77815125, 0.        , 0.60205999]])

In [185]:
np.exp(math1)


array([[  2.71828183, 403.42879349, 148.4131591 ,  20.08553692],
       [ 54.59815003,   7.3890561 ,   7.3890561 ,  20.08553692],
       [  7.3890561 , 403.42879349,   2.71828183,  54.59815003]])

In [186]:
np.sqrt(math1)


array([[1.        , 2.44948974, 2.23606798, 1.73205081],
       [2.        , 1.41421356, 1.41421356, 1.73205081],
       [1.41421356, 2.44948974, 1.        , 2.        ]])

In [188]:
np.power(math1, 2)


array([[ 1, 36, 25,  9],
       [16,  4,  4,  9],
       [ 4, 36,  1, 16]], dtype=int32)

In [189]:
math1


array([[1, 6, 5, 3],
       [4, 2, 2, 3],
       [2, 6, 1, 4]])

In [191]:
np.mean(math1)


3.25

In [192]:
np.median(math1)


3.0

In [193]:
np.std(math1)


1.689427911059441

In [194]:
np.var(math1)


2.8541666666666665

In [195]:
np.min(math1)


1

In [196]:
np.max(math1)


6