In [1]:
import numpy as np


In [2]:
l = [1, 2, 3, 4]
type(l)


list

In [3]:
ar = np.array(l)


In [4]:
print(ar)
type(ar)


[1 2 3 4]


numpy.ndarray

In [5]:
np.asarray(l)


array([1, 2, 3, 4])

In [6]:
np.asanyarray(l)


array([1, 2, 3, 4])

In [7]:
b = np.matrix(l)


In [8]:
b


matrix([[1, 2, 3, 4]])

In [9]:
type(b)


numpy.matrix

In [10]:
a = np.array(l)


In [11]:
a


array([1, 2, 3, 4])

In [12]:
c = a
c


array([1, 2, 3, 4])

In [13]:
a


array([1, 2, 3, 4])

In [14]:
c[0] = 100  # Here c and a are vice versa..They are directly prepotinal ...It refers same address


In [15]:
a


array([100,   2,   3,   4])

In [16]:
c


array([100,   2,   3,   4])

In [17]:
d = np.copy(a)  # Here d and a are refers different address


In [18]:
d


array([100,   2,   3,   4])

In [19]:
d[0] = 200
d


array([200,   2,   3,   4])

In [20]:
a


array([100,   2,   3,   4])

In [21]:
result = np.fromfunction(lambda i, j: (print(i, j), i == j), (3, 3))


[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]] [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [26]:
result = np.fromfunction(lambda i, j: i == j, (3, 3))
result


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [22]:

result = np.fromfunction(lambda i, j: (
    print(f"i: {i}, j: {j}"), i == j), (3, 3))
print(result)


i: [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]], j: [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
(None, array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]]))


In [23]:
import numpy as np
np.fromfunction(lambda i, j: i*j, (3, 3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [58]:
iterable = (i*i for i in range(5))
# np.fromiter(iterable, float)


In [59]:
intVal = np.fromiter(iterable, int)
intVal


array([ 0,  1,  4,  9, 16])

In [60]:
intVal


array([ 0,  1,  4,  9, 16])

In [68]:
np.fromstring("1234 5678", sep=" ")


array([1234., 5678.])

In [69]:
l1 = [[1, 2, 3, 4], [5, 6, 7, 8]]


In [70]:
arr1 = np.array(l1)
arr1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
arr2 = np.array([[101, 102, 103], [201, 202, 203]])
arr2


array([[101, 102, 103],
       [201, 202, 203]])

In [72]:
arr1.size


8

In [73]:
arr2.size


6

In [74]:
arr1.shape


(2, 4)

In [77]:
arr2.shape


numpy.ndarray

In [78]:
arr2.dtype


dtype('int32')

In [81]:
arr3 = np.array([[1.4, 2, 3, 4, 5], [9, 8, 7, 6, 12]])
arr3.dtype()


dtype('float64')

In [93]:
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [99]:
list(np.arange(1.5, 11.2, 1.2))


[1.5,
 2.7,
 3.9000000000000004,
 5.1000000000000005,
 6.300000000000001,
 7.500000000000001,
 8.700000000000001,
 9.900000000000002,
 11.100000000000001]

In [108]:
np.linspace(0, 100, 21)


array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [112]:
np.zeros([3, 4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
# Here 1st Parameter(3)=No. of matrix  2nd Parameter(4)=No.of rows in matrix  3rd Parameter(5)=No.of columns in matrix
np.zeros([3, 5, 3])


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [127]:
# Here 1st Parameter(2)=No. of matrix copies you  hava 2nd Parameter(3)=No.of matrix 3rd Parameter(2)=No.of rows in matrix  3rd Parameter(5)=No.of columns in matrix
np.zeros([2, 3, 2, 3])


array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [122]:
np.ones((5, 3, 2))


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [132]:
on = np.ones((2, 4, 4))
on


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [133]:
on+3


array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [148]:
np.empty((3, 2))


array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [150]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.logspace(3, 1, base=2)


array([8.        , 7.77683793, 7.55990103, 7.34901563, 7.14401294,
       6.94472885, 6.75100385, 6.56268285, 6.37961511, 6.2016541 ,
       6.02865736, 5.8604864 , 5.69700662, 5.53808714, 5.38360077,
       5.23342383, 5.08743612, 4.94552078, 4.8075642 , 4.67345595,
       4.54308869, 4.41635805, 4.2931626 , 4.17340372, 4.05698555,
       3.94381489, 3.83380115, 3.72685628, 3.62289466, 3.52183307,
       3.42359063, 3.32808868, 3.23525079, 3.14500263, 3.05727197,
       2.97198858, 2.88908419, 2.80849244, 2.73014882, 2.65399061,
       2.57995685, 2.50798829, 2.43802731, 2.37001791, 2.30390564,
       2.2396376 , 2.17716233, 2.11642982, 2.05739147, 2.        ])

In [161]:
arr = np.random.rand(2, 3)
arr


array([[0.78131293, 0.71560236, 0.76287959],
       [0.97275536, 0.21880099, 0.12424993]])

In [168]:
randArr1 = np.random.randint(1, 100, (3, 4))
randArr1


array([[17, 74, 74, 96],
       [56, 84, 51, 89],
       [39, 48, 50, 74]])

In [175]:
import pandas as pd
df1 = pd.DataFrame(randArr1).to_csv("randomData.csv")
df3 = pd.read_csv("randomData.csv")
df3.head()


Unnamed: 0   0   1   2   3
0           0  17  74  74  96
1           1  56  84  51  89
2           2  39  48  50  74

In [170]:
df1


0   1   2   3
0  17  74  74  96
1  56  84  51  89
2  39  48  50  74

In [171]:
df2 = pd.DataFrame(arr)


In [172]:
df2


0         1        2
0  0.781313  0.715602  0.76288
1  0.972755  0.218801  0.12425

In [177]:
arr5 = np.random.randint(1, 100, (5, 5))
arr5


array([[46, 62, 87, 71, 38],
       [20,  8, 96, 20, 86],
       [86, 84, 95, 67, 97],
       [34,  5, 43, 67, 23],
       [40, 39, 69, 82, 22]])

In [181]:
arr5.reshape(2, 4)


ValueError: cannot reshape array of size 25 into shape (2,4)

In [5]:
a = 1
a


1